import { describe, expect, it, vi } from "vitest";
import { convertExport } from "../../shared/dtcg/convert";
import { makeFixture } from "../../shared/dtcg/__tests__/fixtures";
import { DEFAULT_SETTINGS, type GitLabSettings } from "../../shared/types";
import { joinRepoPath, type GitLabClient, type TreeEntry } from "../gitlab";
import { buildCommitActions, planPush, pushTokens, serializeFile } from "../push";

const settings: GitLabSettings = {
  ...DEFAULT_SETTINGS,
  instanceUrl: "https://gitlab.example.com",
  projectId: "design-system/tokens",
  targetBranch: "main",
  basePath: "tokens"
};

const files = convertExport(makeFixture()).files;

/** Minimal stand-in for GitLabClient: a virtual repo of raw file contents. */
function fakeClient(repo: Record<string, string>) {
  const tree: TreeEntry[] = Object.keys(repo).map((path) => ({ path, type: "blob" }));
  return {
    listTree: vi.fn(async () => tree),
    getFileContent: vi.fn(async (path: string) => repo[path] ?? null),
    commit: vi.fn(async () => ({ id: "abc123", web_url: "https://gitlab.example.com/commit/abc123" })),
    createBranch: vi.fn(async () => ({})),
    createMergeRequest: vi.fn(async () => ({ iid: 7, web_url: "https://gitlab.example.com/mr/7" }))
  } as unknown as GitLabClient & {
    listTree: ReturnType<typeof vi.fn>;
    getFileContent: ReturnType<typeof vi.fn>;
    commit: ReturnType<typeof vi.fn>;
    createBranch: ReturnType<typeof vi.fn>;
    createMergeRequest: ReturnType<typeof vi.fn>;
  };
}

function repoWithAllFiles(): Record<string, string> {
  return Object.fromEntries(
    files.map((file) => [joinRepoPath("tokens", file.path), serializeFile(file)])
  );
}

describe("joinRepoPath", () => {
  it("prefixes the base path and tolerates slashes", () => {
    expect(joinRepoPath("tokens", "a.tokens.json")).toBe("tokens/a.tokens.json");
    expect(joinRepoPath("/tokens/", "a.tokens.json")).toBe("tokens/a.tokens.json");
    expect(joinRepoPath("", "a.tokens.json")).toBe("a.tokens.json");
  });
});

describe("planPush", () => {
  it("treats an empty repo as all-new and only fetches existing files", async () => {
    const client = fakeClient({});
    const plan = await planPush(client, settings, files);
    expect(plan.hasChanges).toBe(true);
    expect(plan.diffs.every((diff) => diff.status === "new")).toBe(true);
    expect(plan.deletions).toEqual([]);
    expect(client.getFileContent).not.toHaveBeenCalled();
  });

  it("reports no changes when the repo already matches", async () => {
    const plan = await planPush(fakeClient(repoWithAllFiles()), settings, files);
    expect(plan.hasChanges).toBe(false);
    expect(plan.diffs.every((diff) => diff.status === "unchanged")).toBe(true);
  });

  it("detects modified files and stale generated files", async () => {
    const repo = repoWithAllFiles();
    const primPath = "tokens/primitives.tokens.json";
    const parsed = JSON.parse(repo[primPath]);
    parsed.primitives.space.md.$value.value = 24;
    repo[primPath] = JSON.stringify(parsed, null, 2);
    repo["tokens/legacy.tokens.json"] = "{}";
    repo["tokens/README.md"] = "not generated by this plugin";

    const plan = await planPush(fakeClient(repo), settings, files);
    const prim = plan.diffs.find((diff) => diff.path === "primitives.tokens.json")!;
    expect(prim.status).toBe("modified");
    expect(prim.changed).toEqual(["primitives.space.md"]);
    // README.md is left alone; only generated token files are ever deleted.
    expect(plan.deletions).toEqual(["tokens/legacy.tokens.json"]);
  });
});

describe("buildCommitActions", () => {
  it("creates new files, updates changed ones and skips unchanged ones", async () => {
    const repo = repoWithAllFiles();
    delete repo["tokens/styles.tokens.json"];
    const parsed = JSON.parse(repo["tokens/primitives.tokens.json"]);
    parsed.primitives.space.md.$value.value = 24;
    repo["tokens/primitives.tokens.json"] = JSON.stringify(parsed, null, 2);
    repo["tokens/legacy.tokens.json"] = "{}";

    const plan = await planPush(fakeClient(repo), settings, files);
    const actions = buildCommitActions(settings, files, plan);

    expect(actions).toEqual([
      expect.objectContaining({ action: "update", file_path: "tokens/primitives.tokens.json" }),
      expect.objectContaining({ action: "create", file_path: "tokens/styles.tokens.json" }),
      expect.objectContaining({ action: "delete", file_path: "tokens/legacy.tokens.json" })
    ]);
    expect(actions[0].content).toContain('"value": 16');
  });

  it("writes files with a trailing newline", () => {
    expect(serializeFile(files[0]).endsWith("\n")).toBe(true);
  });
});

describe("pushTokens", () => {
  it("commits directly to the target branch in commit flow", async () => {
    const client = fakeClient({});
    const plan = await planPush(client, settings, files);
    const outcome = await pushTokens(client, settings, files, plan, "chore: sync tokens");

    expect(client.createBranch).not.toHaveBeenCalled();
    expect(client.commit).toHaveBeenCalledWith("main", "chore: sync tokens", expect.any(Array));
    expect(outcome).toEqual({ branch: "main", commitUrl: "https://gitlab.example.com/commit/abc123" });
  });

  it("creates a branch, commits there and opens a merge request in mr flow", async () => {
    const mrSettings = { ...settings, flow: "mr" as const };
    const client = fakeClient({});
    const plan = await planPush(client, mrSettings, files);
    const outcome = await pushTokens(client, mrSettings, files, plan, "chore: sync tokens");

    const branch = client.createBranch.mock.calls[0][0] as string;
    expect(branch).toMatch(/^figma-tokens\//);
    expect(client.createBranch).toHaveBeenCalledWith(branch, "main");
    expect(client.commit).toHaveBeenCalledWith(branch, "chore: sync tokens", expect.any(Array));
    expect(client.createMergeRequest).toHaveBeenCalledWith(
      branch,
      "main",
      "chore: sync tokens",
      expect.stringContaining("primitives.tokens.json")
    );
    expect(outcome.mergeRequestUrl).toBe("https://gitlab.example.com/mr/7");
  });

  it("refuses to push when there is nothing to change", async () => {
    const client = fakeClient(repoWithAllFiles());
    const plan = await planPush(client, settings, files);
    await expect(pushTokens(client, settings, files, plan, "noop")).rejects.toThrow(
      /Nothing to push/
    );
    expect(client.commit).not.toHaveBeenCalled();
  });
});
